// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdUUsl6G7VoY6kxDYhLOBJCX3bOEMeEgs',
    appId: '1:124024311494:web:294d9de3b6cb8de52851c7',
    messagingSenderId: '124024311494',
    projectId: 'optimistic-soundz-app',
    authDomain: 'optimistic-soundz-app.firebaseapp.com',
    databaseURL: 'https://optimistic-soundz-app-default-rtdb.firebaseio.com',
    storageBucket: 'optimistic-soundz-app.appspot.com',
    measurementId: 'G-BTF1Z0FRFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW9eTobNz53YX7-K89id2ddeb0hlQLHZQ',
    appId: '1:124024311494:android:c42c5cbbd63b05912851c7',
    messagingSenderId: '124024311494',
    projectId: 'optimistic-soundz-app',
    databaseURL: 'https://optimistic-soundz-app-default-rtdb.firebaseio.com',
    storageBucket: 'optimistic-soundz-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUNdb-PPJJroUXq9ai1fNDFnHlcpfn2-w',
    appId: '1:124024311494:ios:6e58b2444f15c2c42851c7',
    messagingSenderId: '124024311494',
    projectId: 'optimistic-soundz-app',
    databaseURL: 'https://optimistic-soundz-app-default-rtdb.firebaseio.com',
    storageBucket: 'optimistic-soundz-app.appspot.com',
    iosClientId: '124024311494-s3hgmm0k8ntrtj19vehaumelnoth8q8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.optimisticSoundz',
  );
}
